# Generated by Django 2.2.2 on 2019-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, null=True)),
                ('number', models.IntegerField(default=0, max_length=10, unique=True)),
                ('quantity', models.IntegerField(default=0, max_length=20)),
            ],
        ),
    ]
